//! All 12 one-sided pentominoes (F, I, L, N, P, T, U, V, W, X, Y, Z)
//! and their orientation enumeration.
//!
//! Orientations are generated by applying the dihedral group D4 (4 rotations
//! × optional reflection) and deduplicating. Symmetric pieces yield fewer
//! distinct orientations:
//!   1 orientation: X
//!   2 orientations: I
//!   4 orientations: T, U, V, W
//!   8 orientations: F, L, N, P, Y, Z

use std::collections::HashSet;
use std::fmt;

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
)]
pub enum PieceType {
    F,
    I,
    L,
    N,
    P,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
}

impl fmt::Display for PieceType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl PieceType {
    pub fn all() -> &'static [PieceType] {
        use PieceType::*;
        &[F, I, L, N, P, T, U, V, W, X, Y, Z]
    }
}

/// A shape is a sorted list of (row, col) cell offsets, normalized so
/// the minimum row and column are both 0.
pub type Shape = Vec<(i32, i32)>;

pub fn normalize(shape: &mut Shape) {
    let min_r = shape.iter().map(|&(r, _)| r).min().unwrap_or(0);
    let min_c = shape.iter().map(|&(_, c)| c).min().unwrap_or(0);
    for p in shape.iter_mut() {
        p.0 -= min_r;
        p.1 -= min_c;
    }
    shape.sort_unstable();
}

fn rotate90(shape: &Shape) -> Shape {
    let mut result: Shape = shape.iter().map(|&(r, c)| (c, -r)).collect();
    normalize(&mut result);
    result
}

fn reflect(shape: &Shape) -> Shape {
    let mut result: Shape = shape.iter().map(|&(r, c)| (r, -c)).collect();
    normalize(&mut result);
    result
}

/// Returns all distinct orientations of a shape under the dihedral group D4.
pub fn all_orientations(base: Shape) -> Vec<Shape> {
    let mut seen = HashSet::new();
    let mut shapes = Vec::new();
    let mut cur = base;
    for _ in 0..4 {
        if seen.insert(cur.clone()) {
            shapes.push(cur.clone());
        }
        let r = reflect(&cur);
        if seen.insert(r.clone()) {
            shapes.push(r);
        }
        cur = rotate90(&cur);
    }
    shapes
}

/// Canonical base shapes for all 12 pentominoes.
/// Each is normalized (min row = min col = 0, cells sorted).
/// The `all_orientations` function generates the full orbit under D4.
pub fn all_pieces() -> Vec<(PieceType, Vec<Shape>)> {
    use PieceType::*;
    let bases: &[(PieceType, &[(i32, i32)])] = &[
        // F: .##       X: .#.
        //    ##.           ###
        //    .#.           .#.
        (F, &[(0, 1), (0, 2), (1, 0), (1, 1), (2, 1)]),
        // I: #####
        (I, &[(0, 0), (1, 0), (2, 0), (3, 0), (4, 0)]),
        // L: #.
        //    #.
        //    #.
        //    ##
        (L, &[(0, 0), (1, 0), (2, 0), (3, 0), (3, 1)]),
        // N: #.
        //    ##
        //    .#
        //    .#
        (N, &[(0, 0), (1, 0), (1, 1), (2, 1), (3, 1)]),
        // P: ##
        //    ##
        //    #.
        (P, &[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0)]),
        // T: ###
        //    .#.
        //    .#.
        (T, &[(0, 0), (0, 1), (0, 2), (1, 1), (2, 1)]),
        // U: #.#
        //    ###
        (U, &[(0, 0), (0, 2), (1, 0), (1, 1), (1, 2)]),
        // V: #..
        //    #..
        //    ###
        (V, &[(0, 0), (1, 0), (2, 0), (2, 1), (2, 2)]),
        // W: #..
        //    ##.
        //    .##
        (W, &[(0, 0), (1, 0), (1, 1), (2, 1), (2, 2)]),
        // X: .#.
        //    ###
        //    .#.
        (X, &[(0, 1), (1, 0), (1, 1), (1, 2), (2, 1)]),
        // Y: .#
        //    ##
        //    .#
        //    .#
        (Y, &[(0, 1), (1, 0), (1, 1), (2, 1), (3, 1)]),
        // Z: ##.
        //    .#.
        //    .##
        (Z, &[(0, 0), (0, 1), (1, 1), (2, 1), (2, 2)]),
    ];

    bases
        .iter()
        .map(|&(piece_type, cells)| {
            let mut base: Shape = cells.to_vec();
            normalize(&mut base);
            let orientations = all_orientations(base);
            (piece_type, orientations)
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn orientation_counts() {
        let pieces = all_pieces();
        let counts: Vec<(PieceType, usize)> = pieces
            .iter()
            .map(|(t, orients)| (*t, orients.len()))
            .collect();
        // X: 1 (fully symmetric)
        // I: 2 (horizontal/vertical only)
        // T, U, V, W, Z: 4 (Z is point-symmetric: rot180 = identity, so only 2 rotations × 2 mirrors = 4)
        // F, L, N, P, Y: 8 (chiral, no rotational symmetry)
        for (t, count) in &counts {
            let expected = match t {
                PieceType::X => 1,
                PieceType::I => 2,
                PieceType::T | PieceType::U | PieceType::V | PieceType::W | PieceType::Z => 4,
                _ => 8,
            };
            assert_eq!(
                *count, expected,
                "{:?} should have {} orientations",
                t, expected
            );
        }
    }

    #[test]
    fn all_shapes_have_5_cells() {
        for (t, orientations) in all_pieces() {
            for shape in &orientations {
                assert_eq!(shape.len(), 5, "{:?} orientation has wrong cell count", t);
            }
        }
    }
}
